service: lightningtalk

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: '20201221'
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
